### ISSUE TITLE
Where is "Looping parsers" section?

### ISSUE THREAD

**Issue by Bodigrim** [meooow25/parser-regex#33]
[Documentation](https://hackage.haskell.org/package/parser-regex-0.2.0.0/docs/Regex-Base.html) repeatedly mentions `Also see the section "Looping parsers"`, but it's nowhere to be found.

**Comment by meooow25** [comment]
I was just too lazy to repeat it for `Regex.Base`.

You can see it at the bottom of the page on `Regex.List` and `Regex.Text`.

**Comment by Bodigrim** [comment]
Yeah, but the majority of readers will start from `Regex.Base`.

**Comment by Bodigrim** [comment]
> I sure hope not. Most users will not need `Regex.Base`.

`Regex.Base` is the first module in `Regex` namespace, followed by a long trail of `Internal`, which vividly suggests to (unattentive) readers that it is an entry point. At least that's what happened to me. Maybe rename it to `Regex.LowLevel`?.. 

Also it would help to extend 
https://github.com/meooow25/parser-regex/blob/d13c41a7aa7e259486cfdf7ccabcbb691abb0a60/parser-regex.cabal#L5
with suggesting `Regex.List` / `Regex.Text`, because this is the very first sentence a user encounters.
